### ISSUE TITLE
再認実験の結果データについて

### ISSUE THREAD

**Issue by WATANABEMe** [temochiz-lab/watanabe-2022-lesson1-2#1]
望月様
再認実験の結果データ、data.csvについてお尋ねします。
授業で、90台のパソコンで一斉に実施した実験で、エクセルでデータを読み込むときに、UTF-8を指定しても、文字化けが若干残ってしまう場合がありました。
だいたいですが、３５％ぐらいがそうでした。また、カンマ区切りで読み込んでも、ところどころ、answer,correctのｋ、J文字がはいるところが、ずれてしまう場合がありました（刺激文字　たとえば印鑑証明の列の方に、ｋやｊが入ってしまうことがある）。
ずれは手動でなおしました。
全て文字化けなく読み込めれば、このような問題は生じていません。

文字コードの変換がうまくいかないのは、なぜなのかは、大学メディアセンターの方でもわからないのですが、
なにか対策はあるでしょうか。今後にむけて策があれば教えていただきたいです。
また、できればnullの行が出力されないようしていただけるとデータ整理がスムーズになりますが、それは難しいでしょうか？

渡辺

**Comment by temochiz-lab** [comment]
この場合、Excelが怪しいので、メモ帳で開いてBOM付きUTF-8で保存した後に、Excelで開いてみてください。
ファイル先頭にUTF-8を明示するためのBOMが付加されて確実に開けるかと思います。
https://forest.watch.impress.co.jp/docs/news/1157696.html

**Comment by temochiz-lab** [comment]
一括で文字コードを返還するフリーソフトもあるようです。
https://www.oikawa-sekkei.com/web/design/others/convert.html
こちらはご利用前に必ずバックアップを。

**Comment by WATANABEMe** [comment]
データをメモ帳で開いて、UTF-8　BOM付きで保存してから、エクセルで開く、
ということですね。それでちゃんと開けました。沼倉さんにも伝えてあげたいですね。
学生は、エクセルが初めてとか、パソコン自体がほぼなじみのない子もいますので、９０人で一斉に授業するのはなかなかたいへんでした。

報告ですが、お世話になっているタカモリさんですが、パソコン操作が難しいこともあり、実験はやめて質問紙調査のみにする方向になっています。

**Comment by temochiz-lab** [comment]
開き方について、共通レポジトリの扉ページに注釈を入れておきました。
高森さんの件、了解しました。
